export interface FeatureFlagDefinition {
  key: string;
  label: string;
  description: string;
  descriptionI18nKey: string;
  category: "security" | "network" | "policies" | "runtime" | "cli" | "health";
  defaultValue: string;
  type: "boolean" | "enum";
  enumValues?: string[];
  requiresRestart: boolean;
  warningLevel?: "info" | "caution" | "danger";
}

export const FEATURE_FLAG_DEFINITIONS: FeatureFlagDefinition[] = [
  // Security
  {
    key: "REQUIRE_API_KEY",
    label: "Require API Key",
    description: "Enforce API key authentication on all requests.",
    descriptionI18nKey: "settings.featureFlags.requireApiKey",
    category: "security",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "caution",
  },
  {
    key: "INPUT_SANITIZER_ENABLED",
    label: "Input Sanitizer Enabled",
    description: "Enable DOMPurify and input sanitization on requests.",
    descriptionI18nKey: "settings.featureFlags.inputSanitizerEnabled",
    category: "security",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "INJECTION_GUARD_MODE",
    label: "Injection Guard Mode",
    description: "Mode for prompt injection protection.",
    descriptionI18nKey: "settings.featureFlags.injectionGuardMode",
    category: "security",
    defaultValue: "off",
    type: "enum",
    enumValues: ["off", "warn", "block", "redact"],
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "PII_REDACTION_ENABLED",
    label: "PII Redaction Enabled",
    description: "Enable PII redaction on requests.",
    descriptionI18nKey: "settings.featureFlags.piiRedactionEnabled",
    category: "security",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "PII_RESPONSE_SANITIZATION",
    label: "PII Response Sanitization",
    description: "Enable PII sanitization on responses.",
    descriptionI18nKey: "settings.featureFlags.piiResponseSanitization",
    category: "security",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "OUTBOUND_SSRF_GUARD_ENABLED",
    label: "Outbound SSRF Guard Enabled",
    description: "Enable SSRF protection on outbound requests.",
    descriptionI18nKey: "settings.featureFlags.outboundSsrfGuardEnabled",
    category: "security",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },

  // Network
  {
    key: "ENABLE_TLS_FINGERPRINT",
    label: "Enable TLS Fingerprint",
    description: "Stealth TLS fingerprinting PRICING_SYNC_ENABLED.",
    descriptionI18nKey: "settings.featureFlags.enableTlsFingerprint",
    category: "network",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "info",
  },
  {
    key: "ONEPROXY_ENABLED",
    label: "OneProxy Enabled",
    description: "Enable 1proxy request proxying.",
    descriptionI18nKey: "settings.featureFlags.oneproxyEnabled",
    category: "network",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "MITM_DISABLE_TLS_VERIFY",
    label: "MITM Disable TLS Verify",
    description: "Disable TLS verification in MITM proxy.",
    descriptionI18nKey: "settings.featureFlags.mitmDisableTlsVerify",
    category: "network",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "danger",
  },
  {
    key: "OMNIROUTE_ALLOW_PRIVATE_PROVIDER_URLS",
    label: "Allow Private Provider URLs",
    description: "Allow internal IP networks for provider API Base URLs.",
    descriptionI18nKey: "settings.featureFlags.allowPrivateProviderUrls",
    category: "network",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "caution",
  },
  {
    key: "ENABLE_CC_COMPATIBLE_PROVIDER",
    label: "Enable CC Compatible Provider",
    description: "Provider UI for Claude Code-only relays.",
    descriptionI18nKey: "settings.featureFlags.enableCcCompatibleProvider",
    category: "network",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },

  // Policies
  {
    key: "TOOL_POLICY_MODE",
    label: "Tool Policy Mode",
    description: "Enforce policies on AI tool usage.",
    descriptionI18nKey: "settings.featureFlags.toolPolicyMode",
    category: "policies",
    defaultValue: "disabled",
    type: "enum",
    enumValues: ["disabled", "warn", "block"],
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "RATE_LIMIT_AUTO_ENABLE",
    label: "Rate Limit Auto Enable",
    description: "Automatically enable rate limiting when traffic spikes.",
    descriptionI18nKey: "settings.featureFlags.rateLimitAutoEnable",
    category: "policies",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "ALLOW_MULTI_CONNECTIONS_PER_COMPAT_NODE",
    label: "Allow Multi Connections Per Compat Node",
    description: "Allow multiple connections per compatible node.",
    descriptionI18nKey: "settings.featureFlags.allowMultiConnectionsPerCompatNode",
    category: "policies",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },

  // Runtime
  {
    key: "OMNIROUTE_MCP_ENFORCE_SCOPES",
    label: "MCP Enforce Scopes",
    description: "Enforce authorization scopes on MCP server tools.",
    descriptionI18nKey: "settings.featureFlags.mcpEnforceScopes",
    category: "runtime",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "caution",
  },
  {
    key: "OMNIROUTE_MCP_COMPRESS_DESCRIPTIONS",
    label: "MCP Compress Descriptions",
    description: "Compress tool descriptions in MCP definitions to save tokens.",
    descriptionI18nKey: "settings.featureFlags.mcpCompressDescriptions",
    category: "runtime",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "info",
  },
  {
    key: "OMNIROUTE_ENABLE_RUNTIME_BACKGROUND_TASKS",
    label: "Enable Runtime Background Tasks",
    description: "Allow long-running background execution for async tasks.",
    descriptionI18nKey: "settings.featureFlags.enableRuntimeBackgroundTasks",
    category: "runtime",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "info",
  },
  {
    key: "OMNIROUTE_DISABLE_BACKGROUND_SERVICES",
    label: "Disable Background Services",
    description: "Force disable all background services and periodic jobs.",
    descriptionI18nKey: "settings.featureFlags.disableBackgroundServices",
    category: "runtime",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "caution",
  },
  {
    key: "OMNIROUTE_RTK_TRUST_PROJECT_FILTERS",
    label: "RTK Trust Project Filters",
    description: "Trust project-specific RTK filters in workspace directories.",
    descriptionI18nKey: "settings.featureFlags.rtkTrustProjectFilters",
    category: "runtime",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "caution",
  },

  // CLI
  {
    key: "CLI_COMPAT_ALL",
    label: "CLI Compat All",
    description: "Enable compatibility features for all supported CLIs.",
    descriptionI18nKey: "settings.featureFlags.cliCompatAll",
    category: "cli",
    defaultValue: "0",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "MODEL_ALIAS_COMPAT_ENABLED",
    label: "Model Alias Compat Enabled",
    description: "Enable strict model alias compatibility for older CLIs.",
    descriptionI18nKey: "settings.featureFlags.modelAliasCompatEnabled",
    category: "cli",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "PRICING_SYNC_ENABLED",
    label: "Pricing Sync Enabled",
    description: "Auto sync model pricing information from remote source.",
    descriptionI18nKey: "settings.featureFlags.pricingSyncEnabled",
    category: "cli",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },

  // Health
  {
    key: "OMNIROUTE_DISABLE_LOCAL_HEALTHCHECK",
    label: "Disable Local Healthcheck",
    description: "Disable localhost healthcheck endpoint polling.",
    descriptionI18nKey: "settings.featureFlags.disableLocalHealthcheck",
    category: "health",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: true,
    warningLevel: "info",
  },
  {
    key: "OMNIROUTE_DISABLE_TOKEN_HEALTHCHECK",
    label: "Disable Token Healthcheck",
    description: "Disable automated proactive token healthchecks.",
    descriptionI18nKey: "settings.featureFlags.disableTokenHealthcheck",
    category: "health",
    defaultValue: "false",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "info",
  },
  {
    key: "SKILLS_SANDBOX_NETWORK_ENABLED",
    label: "Skills Sandbox Network Enabled",
    description: "Allow outbound network access from isolated skill sandboxes.",
    descriptionI18nKey: "settings.featureFlags.skillsSandboxNetworkEnabled",
    category: "health",
    defaultValue: "0",
    type: "boolean",
    requiresRestart: false,
    warningLevel: "caution",
  },
];
